let
    Source = Json.Document(File.Contents("D:\Documents\Programming is fun\all_jira_issues.json")),
    #"Converted to Table" = Table.FromRecords({Source}),
    #"Expanded issues" = Table.ExpandListColumn(#"Converted to Table", "issues"),
    #"Expanded issues1" = Table.ExpandRecordColumn(#"Expanded issues", "issues", {"id", "key", "fields"}, {"issues.id", "issues.key", "issues.fields"}),
    #"Expanded issues.fields" = Table.ExpandRecordColumn(#"Expanded issues1", "issues.fields", {"statuscategorychangedate", "issuetype", "parent", "timespent", "project", "customfield_10031", "fixVersions", "aggregatetimespent", "resolution", "customfield_10027", "customfield_10028", "customfield_10029", "resolutiondate", "workratio", "watches", "lastViewed", "created", "customfield_10020", "customfield_10021", "customfield_10022", "priority", "customfield_10023", "customfield_10024", "customfield_10025", "customfield_10026", "labels", "customfield_10016", "customfield_10017", "customfield_10018", "customfield_10019", "aggregatetimeoriginalestimate", "timeestimate", "versions", "issuelinks", "assignee", "updated", "status", "components", "timeoriginalestimate", "description", "customfield_10010", "customfield_10014", "customfield_10015", "customfield_10005", "customfield_10006", "customfield_10007", "security", "customfield_10008", "customfield_10009", "aggregatetimeestimate", "summary", "creator", "subtasks", "reporter", "aggregateprogress", "customfield_10001", "customfield_10002", "customfield_10003", "customfield_10004", "environment", "duedate", "progress", "votes"}, {"issues.fields.statuscategorychangedate", "issues.fields.issuetype", "issues.fields.parent", "issues.fields.timespent", "issues.fields.project", "issues.fields.customfield_10031", "issues.fields.fixVersions", "issues.fields.aggregatetimespent", "issues.fields.resolution", "issues.fields.customfield_10027", "issues.fields.customfield_10028", "issues.fields.customfield_10029", "issues.fields.resolutiondate", "issues.fields.workratio", "issues.fields.watches", "issues.fields.lastViewed", "issues.fields.created", "issues.fields.customfield_10020", "issues.fields.customfield_10021", "issues.fields.customfield_10022", "issues.fields.priority", "issues.fields.customfield_10023", "issues.fields.customfield_10024", "issues.fields.customfield_10025", "issues.fields.customfield_10026", "issues.fields.labels", "issues.fields.customfield_10016", "issues.fields.customfield_10017", "issues.fields.customfield_10018", "issues.fields.customfield_10019", "issues.fields.aggregatetimeoriginalestimate", "issues.fields.timeestimate", "issues.fields.versions", "issues.fields.issuelinks", "issues.fields.assignee", "issues.fields.updated", "issues.fields.status", "issues.fields.components", "issues.fields.timeoriginalestimate", "issues.fields.description", "issues.fields.customfield_10010", "issues.fields.customfield_10014", "issues.fields.customfield_10015", "issues.fields.customfield_10005", "issues.fields.customfield_10006", "issues.fields.customfield_10007", "issues.fields.security", "issues.fields.customfield_10008", "issues.fields.customfield_10009", "issues.fields.aggregatetimeestimate", "issues.fields.summary", "issues.fields.creator", "issues.fields.subtasks", "issues.fields.reporter", "issues.fields.aggregateprogress", "issues.fields.customfield_10001", "issues.fields.customfield_10002", "issues.fields.customfield_10003", "issues.fields.customfield_10004", "issues.fields.environment", "issues.fields.duedate", "issues.fields.progress", "issues.fields.votes"}),
    #"Expanded issues.fields.issuetype" = Table.ExpandRecordColumn(#"Expanded issues.fields", "issues.fields.issuetype", {"self", "id", "description", "iconUrl", "name", "subtask", "avatarId", "entityId", "hierarchyLevel"}, {"issues.fields.issuetype.self", "issues.fields.issuetype.id", "issues.fields.issuetype.description", "issues.fields.issuetype.iconUrl", "issues.fields.issuetype.name", "issues.fields.issuetype.subtask", "issues.fields.issuetype.avatarId", "issues.fields.issuetype.entityId", "issues.fields.issuetype.hierarchyLevel"}),
    #"Expanded issues.fields.parent" = Table.ExpandRecordColumn(#"Expanded issues.fields.issuetype", "issues.fields.parent", {"id", "key", "self", "fields"}, {"issues.fields.parent.id", "issues.fields.parent.key", "issues.fields.parent.self", "issues.fields.parent.fields"}),
    #"Expanded issues.fields.parent.fields" = Table.ExpandRecordColumn(#"Expanded issues.fields.parent", "issues.fields.parent.fields", {"summary", "status", "priority", "issuetype"}, {"issues.fields.parent.fields.summary", "issues.fields.parent.fields.status", "issues.fields.parent.fields.priority", "issues.fields.parent.fields.issuetype"}),
    #"Expanded issues.fields.parent.fields.status" = Table.ExpandRecordColumn(#"Expanded issues.fields.parent.fields", "issues.fields.parent.fields.status", {"self", "description", "iconUrl", "name", "id", "statusCategory"}, {"issues.fields.parent.fields.status.self", "issues.fields.parent.fields.status.description", "issues.fields.parent.fields.status.iconUrl", "issues.fields.parent.fields.status.name", "issues.fields.parent.fields.status.id", "issues.fields.parent.fields.status.statusCategory"}),
    #"Expanded issues.fields.parent.fields.status.statusCategory" = Table.ExpandRecordColumn(#"Expanded issues.fields.parent.fields.status", "issues.fields.parent.fields.status.statusCategory", {"self", "id", "key", "colorName", "name"}, {"issues.fields.parent.fields.status.statusCategory.self", "issues.fields.parent.fields.status.statusCategory.id", "issues.fields.parent.fields.status.statusCategory.key", "issues.fields.parent.fields.status.statusCategory.colorName", "issues.fields.parent.fields.status.statusCategory.name"}),
    #"Expanded issues.fields.parent.fields.priority" = Table.ExpandRecordColumn(#"Expanded issues.fields.parent.fields.status.statusCategory", "issues.fields.parent.fields.priority", {"self", "iconUrl", "name", "id"}, {"issues.fields.parent.fields.priority.self", "issues.fields.parent.fields.priority.iconUrl", "issues.fields.parent.fields.priority.name", "issues.fields.parent.fields.priority.id"}),
    #"Expanded issues.fields.parent.fields.issuetype" = Table.ExpandRecordColumn(#"Expanded issues.fields.parent.fields.priority", "issues.fields.parent.fields.issuetype", {"self", "id", "description", "iconUrl", "name", "subtask", "avatarId", "entityId", "hierarchyLevel"}, {"issues.fields.parent.fields.issuetype.self", "issues.fields.parent.fields.issuetype.id", "issues.fields.parent.fields.issuetype.description", "issues.fields.parent.fields.issuetype.iconUrl", "issues.fields.parent.fields.issuetype.name", "issues.fields.parent.fields.issuetype.subtask", "issues.fields.parent.fields.issuetype.avatarId", "issues.fields.parent.fields.issuetype.entityId", "issues.fields.parent.fields.issuetype.hierarchyLevel"}),
    #"Expanded issues.fields.project" = Table.ExpandRecordColumn(#"Expanded issues.fields.parent.fields.issuetype", "issues.fields.project", {"self", "id", "key", "name", "projectTypeKey", "simplified", "avatarUrls"}, {"issues.fields.project.self", "issues.fields.project.id", "issues.fields.project.key", "issues.fields.project.name", "issues.fields.project.projectTypeKey", "issues.fields.project.simplified", "issues.fields.project.avatarUrls"}),
    #"Expanded issues.fields.project.avatarUrls" = Table.ExpandRecordColumn(#"Expanded issues.fields.project", "issues.fields.project.avatarUrls", {"48x48", "24x24", "16x16", "32x32"}, {"issues.fields.project.avatarUrls.48x48", "issues.fields.project.avatarUrls.24x24", "issues.fields.project.avatarUrls.16x16", "issues.fields.project.avatarUrls.32x32"}),
    #"Expanded issues.fields.watches" = Table.ExpandRecordColumn(#"Expanded issues.fields.project.avatarUrls", "issues.fields.watches", {"self", "watchCount", "isWatching"}, {"issues.fields.watches.self", "issues.fields.watches.watchCount", "issues.fields.watches.isWatching"}),
    #"Expanded issues.fields.priority" = Table.ExpandRecordColumn(#"Expanded issues.fields.watches", "issues.fields.priority", {"self", "iconUrl", "name", "id"}, {"issues.fields.priority.self", "issues.fields.priority.iconUrl", "issues.fields.priority.name", "issues.fields.priority.id"}),
    #"Expanded issues.fields.customfield_10018" = Table.ExpandRecordColumn(#"Expanded issues.fields.priority", "issues.fields.customfield_10018", {"hasEpicLinkFieldDependency", "showField", "nonEditableReason"}, {"issues.fields.customfield_10018.hasEpicLinkFieldDependency", "issues.fields.customfield_10018.showField", "issues.fields.customfield_10018.nonEditableReason"}),
    #"Expanded issues.fields.customfield_10018.nonEditableReason" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_10018", "issues.fields.customfield_10018.nonEditableReason", {"reason", "message"}, {"issues.fields.customfield_10018.nonEditableReason.reason", "issues.fields.customfield_10018.nonEditableReason.message"}),
    #"Expanded issues.fields.status" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_10018.nonEditableReason", "issues.fields.status", {"self", "description", "iconUrl", "name", "id", "statusCategory"}, {"issues.fields.status.self", "issues.fields.status.description", "issues.fields.status.iconUrl", "issues.fields.status.name", "issues.fields.status.id", "issues.fields.status.statusCategory"}),
    #"Expanded issues.fields.status.statusCategory" = Table.ExpandRecordColumn(#"Expanded issues.fields.status", "issues.fields.status.statusCategory", {"self", "id", "key", "colorName", "name"}, {"issues.fields.status.statusCategory.self", "issues.fields.status.statusCategory.id", "issues.fields.status.statusCategory.key", "issues.fields.status.statusCategory.colorName", "issues.fields.status.statusCategory.name"}),
    #"Expanded issues.fields.creator" = Table.ExpandRecordColumn(#"Expanded issues.fields.status.statusCategory", "issues.fields.creator", {"self", "accountId", "emailAddress", "avatarUrls", "displayName", "active", "timeZone", "accountType"}, {"issues.fields.creator.self", "issues.fields.creator.accountId", "issues.fields.creator.emailAddress", "issues.fields.creator.avatarUrls", "issues.fields.creator.displayName", "issues.fields.creator.active", "issues.fields.creator.timeZone", "issues.fields.creator.accountType"}),
    #"Expanded issues.fields.creator.avatarUrls" = Table.ExpandRecordColumn(#"Expanded issues.fields.creator", "issues.fields.creator.avatarUrls", {"48x48", "24x24", "16x16", "32x32"}, {"issues.fields.creator.avatarUrls.48x48", "issues.fields.creator.avatarUrls.24x24", "issues.fields.creator.avatarUrls.16x16", "issues.fields.creator.avatarUrls.32x32"}),
    #"Expanded issues.fields.reporter" = Table.ExpandRecordColumn(#"Expanded issues.fields.creator.avatarUrls", "issues.fields.reporter", {"self", "accountId", "emailAddress", "avatarUrls", "displayName", "active", "timeZone", "accountType"}, {"issues.fields.reporter.self", "issues.fields.reporter.accountId", "issues.fields.reporter.emailAddress", "issues.fields.reporter.avatarUrls", "issues.fields.reporter.displayName", "issues.fields.reporter.active", "issues.fields.reporter.timeZone", "issues.fields.reporter.accountType"}),
    #"Expanded issues.fields.reporter.avatarUrls" = Table.ExpandRecordColumn(#"Expanded issues.fields.reporter", "issues.fields.reporter.avatarUrls", {"48x48", "24x24", "16x16", "32x32"}, {"issues.fields.reporter.avatarUrls.48x48", "issues.fields.reporter.avatarUrls.24x24", "issues.fields.reporter.avatarUrls.16x16", "issues.fields.reporter.avatarUrls.32x32"}),
    #"Expanded issues.fields.aggregateprogress" = Table.ExpandRecordColumn(#"Expanded issues.fields.reporter.avatarUrls", "issues.fields.aggregateprogress", {"progress", "total"}, {"issues.fields.aggregateprogress.progress", "issues.fields.aggregateprogress.total"}),
    #"Expanded issues.fields.progress" = Table.ExpandRecordColumn(#"Expanded issues.fields.aggregateprogress", "issues.fields.progress", {"progress", "total"}, {"issues.fields.progress.progress", "issues.fields.progress.total"}),
    #"Expanded issues.fields.votes" = Table.ExpandRecordColumn(#"Expanded issues.fields.progress", "issues.fields.votes", {"self", "votes", "hasVoted"}, {"issues.fields.votes.self", "issues.fields.votes.votes", "issues.fields.votes.hasVoted"}),
    #"Expanded issues.fields.customfield_10004" = Table.ExpandRecordColumn(#"Expanded issues.fields.votes", "issues.fields.customfield_10004", {"self", "value", "id"}, {"issues.fields.customfield_10004.self", "issues.fields.customfield_10004.value", "issues.fields.customfield_10004.id"}),
    #"Expanded issues.fields.customfield_10003" = Table.ExpandListColumn(#"Expanded issues.fields.customfield_10004", "issues.fields.customfield_10003"),
    #"Expanded issues.fields.customfield_1" = Table.ExpandRecordColumn(#"Expanded issues.fields.customfield_10003", "issues.fields.customfield_10003", {"self", "accountId", "emailAddress", "avatarUrls", "displayName", "active", "timeZone", "accountType"}, {"issues.fields.customfield_10003.self", "issues.fields.customfield_10003.accountId", "issues.fields.customfield_10003.emailAddress", "issues.fields.customfield_10003.avatarUrls", "issues.fields.customfield_10003.displayName", "issues.fields.customfield_10003.active", "issues.fields.customfield_10003.timeZone", "issues.fields.customfield_10003.accountType"})
in
    #"Expanded issues.fields.customfield_1"
